pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                script {
                    docker.image('golang:1.21').inside {
                        dir('bugtraker-backend') {
                            sh 'go version'   
                            sh 'go test -v ./...'
                        }
                    }
                }
                dir('bugtraker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}

